name: build-test-release

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version: 1.0.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create subfolder
        run: mkdir my-package

      - name: Install UCC and Slim
        run: |
          pip install splunk-add-on-ucc-framework
          pip install splunk-packaging-toolkit

      - name: Build an app using UCC
        run: ucc-gen build

      - name: Create tmp folder
        run: mkdir app-dir
      
      - name: Create package
        run: ucc-gen package --path output/devtutorial_conf24 -o app-dir/

      - name: Debug Workspace Contents
        run: |
          ls -la .
          ls -la app-dir/
      
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: my-package
          path: app-dir/
  
  run-appinspect:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Download package
          uses: actions/download-artifact@v4
          with:
            name: my-package
            path: app-dir/

        - name: Install system packages
          run: |
            echo "github.ref: ${{ github.ref }}"
            echo "github.event.ref: ${{ github.event.ref }}"
            sudo apt update -qq
            sudo apt install -y python3-pip
            sudo pip install splunk-appinspect
        
        - name: Run AppInspect
          run: |
            ls -la .
            ls -la app-dir/
            FILE_NAME=$(ls -1 app-dir/)
            splunk-appinspect inspect app-dir/$FILE_NAME --output-file appinspect_result.json --mode test

        - name: Check contents
          run: |
            ls -la app-dir/
            ls -la .

        - name: Upload appinspect report
          uses: actions/upload-artifact@v4
          with:
            name: appinspect report
            path: appinspect_result.json

